version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST= db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
      - MYSQL_DB= chilpost-sb
      - MYSQL_PORT= 3306
    secrets:
      - db-password
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_TCP_PORT=3306
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_DATABASE=chilpost-sb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 4446:3306
    healthcheck:
      test: [ CMD, mysqladmin, ping, -h, localhost ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
