services:
  api:
    container_name: chilpost_sb
    build: 
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3336/chilpost_sb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_USERNAME=root

  mysql:
    image: mysql:8.2.0
    container_name: chilpost_mysql
    restart: always
    environment:
      - MYSQL_TCP_PORT=3336
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_DATABASE=chilpost_sb
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - chilpost-data:/var/lib/mysql
    ports:
      - 4446:3336
    healthcheck:
      test: [ CMD, mysqladmin, ping, -h, localhost ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  chilpost-data:
    external: true
secrets:
  db-password:
    file: password.txt
