spring:
  exposed:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/chilpost
    username: root
    password: CHILLSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    problemdetails:
      enabled: true