spring:
  exposed:
    generate-ddl: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/chilpost_sb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 5000
  mvc:
    problemdetails:
      enabled: true
server:
  error:
    whitelabel:
      enabled: false
